---
name: wing-language-server
description: A programming language for the cloud
homepage: https://www.winglang.io
licenses:
  - MIT
languages:
  - Wing
categories:
  - LSP

source:
  id: pkg:npm/winglang@0.85.34

schemas:
  lsp: vscode:https://raw.githubusercontent.com/winglang/wing/main/packages/vscode-wing/package.json

bin:
  wing: npm:wing
